server:
  port: 80
  servlet:
   context-path: /momolearn
   multipart:
    enabled: true # 멀티파트 업로드 지원여부 (default: true)
    location: src/main/webapp/img #업로드된 파일의 임시 저장 경로
    max-file-size: 10MB #파일의 최대 사이즈 (default: 1MB)
    max-request-size: 10MB #요청의 최대 사이즈 (default: 10MB)
    
upload:
 path: "src/main/webapp/img"
    
spring:
  profiles:
   include: db
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    hiddenmethod:
      filter:
        enabled: true
  jackson:
    # LocalDateTime 타입의 값을 JSON 형식으로 직렬화할 때, 다음과 같은 형식으로 변환 
    date-time-format: yyyy-MM-dd'T'HH:mm
    
iamport:
 apiKey: 5152205600233867
 apiSecret: OsLhXqsOGXne0bgJ1qsRu9FAUU2FnBpmBVsGV0aJEcFPeDhj88mqvxYaLhUPL0X4s0xj2DU8rjtgpq21
    
#logging:
#  level:
#    org:
#      hibernate: info
#      
## p6spy 사용을 위한 설정
#decorator.datasource.p6spy.enable-logging: true  # false : Disable p6spy
